export { default as Header } from './Header'
export { default as Footer } from './Footer'
export { Container } from './Container'
export { Section } from './Section'
export { CinemaNav } from './CinemaNav'
